### ISSUE TITLE
can't work on laravel 5.5

### ISSUE THREAD

**Issue by lidelin** [caffeinated/repository#12]
Problem 1
    - Conclusion: don't install caffeinated/repository v3.1.1
    - Conclusion: remove laravel/framework v5.5.8
    - Installation request for caffeinated/repository ^3.1 -> satisfiable by caffeinated/repository[v3.1, v3.1.1].
    - Conclusion: don't install laravel/framework v5.5.8
    - caffeinated/repository v3.1 requires illuminate/config 5.4.* -> satisfiable by illuminate/config[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - don't install illuminate/config v5.4.0|don't install laravel/framework v5.5.8
    - don't install illuminate/config v5.4.13|don't install laravel/framework v5.5.8
    - don't install illuminate/config v5.4.17|don't install laravel/framework v5.5.8
    - don't install illuminate/config v5.4.19|don't install laravel/framework v5.5.8
    - don't install illuminate/config v5.4.27|don't install laravel/framework v5.5.8
    - don't install illuminate/config v5.4.36|don't install laravel/framework v5.5.8
    - don't install illuminate/config v5.4.9|don't install laravel/framework v5.5.8
    - Installation request for laravel/framework (locked at v5.5.8, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.8].

**Comment by 1giba** [comment]
https://github.com/caffeinated/repository/pull/13 Laravel 5.5 support

**Comment by kaidesu** [comment]
merged 👍
